language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: pascal@bloob.io
  api_key: YOUR API KEY
  on:
    tags: true
env:
  - "WfkYjUSagj4OEMeU34lUnEGUbc4Mnm22uCeyVt3Ds5o+1tI3RYdMv9P85qkUZINIurw8a
975Po8da92NeJmRzlSmkp1oDHp2hQfQpXvv/yp2tqD7Rw4ac4ZslloFL6WlvrLcMRffm5WkArpRMdKnl
cLtxPOM0bFraCFNdmh7Y+k="
