language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: pascal@bloob.io
  api_key: YOUR API KEY
  on:
    tags: true
dd:
  secure: ZceJe6+9nY06p0BCcg5FY06Vb2PyupmD7KmfTlgNdXjohBCRhlLi9grHShnQkYIH2Tk4wdyTgftHIjwOoYj8ZI3W1JZH3+BOV1WXIGZ42C+DDHRL1OA0ZDVyUBCd+bgUYRN1iZ+h/tg5Ix6aYm/qEM+wvB5dAzmuBVs/z2VnZWM=
